// 71 critérios distribuídos em 16 categorias
// Baseado em WCAG 2.2 + eMAG + LBI
window.CHECKLIST_DATA = [
  {
    cat: 'Semântica',
    wcag: '1.3.1',
    level: 'A',
    title: 'Use elementos HTML nativos sempre que possível',
    detail: 'Prefira <button>, <nav>, <main>, <header> a <div role="...">. O elemento nativo já traz papel, teclado e estados acessíveis por padrão. Só use ARIA quando o HTML nativo não expressa a intenção.',
  },
  {
    cat: 'Semântica',
    wcag: '1.3.1',
    level: 'A',
    title: 'Hierarquia de headings sem pular níveis',
    detail: 'A ordem deve ser H1 → H2 → H3... Nunca pule de H1 para H3. Há exatamente 1 H1 por página, representando o assunto principal.',
  },
  {
    cat: 'Semântica',
    wcag: '1.3.1',
    level: 'A',
    title: 'Landmarks presentes: header, nav, main, footer',
    detail: 'Leitores de tela navegam entre landmarks com atalhos de teclado. Ter <main> único é obrigatório; o conteúdo principal fora de <main> é invisível para navegação estrutural.',
  },
  {
    cat: 'Semântica',
    wcag: '1.3.1',
    level: 'A',
    title: 'Listas reais para conteúdo em lista',
    detail: 'Sequências de itens usam <ul>, <ol> ou <dl> — nunca <div> empilhado. O leitor de tela anuncia "lista com N itens" e permite navegação item-a-item.',
  },
  {
    cat: 'Teclado',
    wcag: '2.1.1',
    level: 'A',
    title: 'Todo controle é operável por teclado',
    detail: 'Tab navega, Enter/Space aciona. Nenhuma funcionalidade depende exclusivamente do mouse. Inclui menus, sliders, modais, drag-and-drop (que deve ter alternativa clicável).',
  },
  {
    cat: 'Teclado',
    wcag: '2.1.2',
    level: 'A',
    title: 'Sem armadilhas de foco',
    detail: 'O foco nunca fica preso num componente sem Esc ou Tab de saída. Modais abrem, aprisionam foco dentro, devolvem ao gatilho ao fechar.',
  },
  {
    cat: 'Teclado',
    wcag: '2.4.7',
    level: 'AA',
    title: 'Foco visível em 100% dos controles interativos',
    detail: 'Outline de 3px mínimo, offset de 2px, cor com contraste ≥ 3:1 contra o fundo. Jamais "outline: none" sem substituto.',
  },
  {
    cat: 'Teclado',
    wcag: '2.4.3',
    level: 'A',
    title: 'Ordem de foco é lógica e previsível',
    detail: 'Tab segue a ordem visual (esquerda→direita, cima→baixo). Nunca use tabindex > 0 — quebra a ordem natural do DOM.',
  },
  {
    cat: 'Teclado',
    wcag: '2.4.1',
    level: 'A',
    title: 'Skip link visível ao receber foco',
    detail: 'Primeiro elemento focável da página. "Pular para o conteúdo" aparece no topo quando recebe Tab e leva direto ao <main>.',
  },
  {
    cat: 'Contraste',
    wcag: '1.4.3',
    level: 'AA',
    title: 'Texto normal com contraste ≥ 4.5:1 (WCAG) ou Lc 75+ (APCA)',
    detail: 'Corpo de texto, labels, placeholders. APCA é mais preciso perceptualmente — recomendamos Lc 75 para body em light e Lc 60 em dark.',
  },
  {
    cat: 'Contraste',
    wcag: '1.4.11',
    level: 'AA',
    title: 'Componentes UI e estados com contraste ≥ 3:1',
    detail: 'Bordas de inputs, ícones funcionais, indicadores de estado. Um checkbox desmarcado precisa ser distinguível do fundo.',
  },
  {
    cat: 'Contraste',
    wcag: '1.4.1',
    level: 'A',
    title: 'Cor nunca é o único canal de informação',
    detail: 'Estados de erro, sucesso, alerta combinam sempre: cor + ícone + texto. Daltônicos, leitores de tela e usuários em ambientes claros dependem disso.',
  },
  {
    cat: 'Formulários',
    wcag: '3.3.2',
    level: 'A',
    title: 'Todo input tem <label> associado',
    detail: 'Via "for" apontando para id do input, ou com o input dentro do label. Placeholder NÃO é label — ele some quando o usuário começa a digitar.',
  },
  {
    cat: 'Formulários',
    wcag: '3.3.1',
    level: 'A',
    title: 'Erros identificados em texto, não só em cor',
    detail: 'Mensagem abaixo do campo, ícone de alerta, aria-describedby conectando input à mensagem. Liste todos os erros no topo como sumário.',
  },
  {
    cat: 'Formulários',
    wcag: '3.3.3',
    level: 'AA',
    title: 'Sugestão de correção quando possível',
    detail: 'CEP inválido → mostre formato esperado. Email → sugira domínio comum. Não apenas "campo inválido".',
  },
  {
    cat: 'Formulários',
    wcag: '1.3.5',
    level: 'AA',
    title: 'Autocomplete em campos de dados pessoais',
    detail: 'autocomplete="name", "email", "tel", "cpf"... Ajuda gerenciadores de senha e pessoas com dislexia ou TDAH.',
  },
  {
    cat: 'Imagens',
    wcag: '1.1.1',
    level: 'A',
    title: 'Toda imagem informativa tem alt descritivo',
    detail: 'O alt descreve o conteúdo E a função. "Gráfico de barras mostrando X crescendo 40% em Y" — não "imagem".',
  },
  {
    cat: 'Imagens',
    wcag: '1.1.1',
    level: 'A',
    title: 'Imagens decorativas têm alt vazio',
    detail: 'alt="" (explicitamente vazio) faz leitores de tela pularem. Omitir o atributo faz muitos leitores anunciarem o nome do arquivo.',
  },
  {
    cat: 'Imagens',
    wcag: '1.4.5',
    level: 'AA',
    title: 'Evite texto em imagem',
    detail: 'Texto real escalona, é traduzível, tem contraste verificável. Use imagem apenas quando o visual específico for essencial (logos, citações estilizadas).',
  },
  {
    cat: 'Mídia',
    wcag: '1.2.2',
    level: 'A',
    title: 'Vídeos com legendas sincronizadas',
    detail: 'Formato .vtt, legendas descrevem diálogo E sons relevantes ("[música tensa]", "[porta batendo]"). Legendas automáticas do YouTube não são suficientes.',
  },
  {
    cat: 'Mídia',
    wcag: '1.2.3',
    level: 'A',
    title: 'Audiodescrição para informação visual relevante',
    detail: 'Quando o vídeo mostra algo que o áudio não diz, adicione faixa de audiodescrição. LIBRAS é opcional mas altamente recomendado no Brasil.',
  },
  {
    cat: 'Mídia',
    wcag: '1.4.2',
    level: 'A',
    title: 'Áudio não toca automaticamente por mais de 3s',
    detail: 'Autoplay interfere com leitores de tela. Se tocar, deve haver pausa/stop sempre visível, ou duração < 3s.',
  },
  {
    cat: 'Navegação',
    wcag: '2.4.2',
    level: 'A',
    title: 'Título único e descritivo por página',
    detail: '<title> descreve conteúdo + site. "Checklist · acessibilidade.online" — não "Home" ou "Untitled".',
  },
  {
    cat: 'Navegação',
    wcag: '2.4.4',
    level: 'A',
    title: 'Texto de link descreve o destino',
    detail: 'Nunca "clique aqui" ou "saiba mais". "Baixar relatório em PDF" ou "Ler sobre a LBI" — o link faz sentido fora de contexto.',
  },
  {
    cat: 'Navegação',
    wcag: '2.4.8',
    level: 'AAA',
    title: 'Breadcrumb em páginas profundas',
    detail: 'Mostra onde o usuário está na hierarquia e permite voltar. Marque com <nav aria-label="Breadcrumb">.',
  },
  {
    cat: 'Navegação',
    wcag: '3.2.3',
    level: 'AA',
    title: 'Navegação consistente entre páginas',
    detail: 'Menu principal na mesma posição, nos mesmos itens, mesma ordem. Usuários com cognição atípica dependem de previsibilidade.',
  },
  {
    cat: 'Motion',
    wcag: '2.3.3',
    level: 'AAA',
    title: 'Respeita prefers-reduced-motion',
    detail: 'Quando o SO pede redução de movimento, transições acima de 100ms são desativadas, paralaxes viram estáticos, autoplay de vídeo para.',
  },
  {
    cat: 'Motion',
    wcag: '2.3.1',
    level: 'A',
    title: 'Nada pisca mais de 3 vezes por segundo',
    detail: 'Conteúdo que pisca na faixa de 3–49Hz pode disparar convulsões fotossensíveis. Evite totalmente.',
  },
  {
    cat: 'Motion',
    wcag: '2.2.2',
    level: 'A',
    title: 'Carrosséis auto-rotativos podem ser pausados',
    detail: 'Botão de pausa visível e focável. Rotação para automaticamente ao foco/hover.',
  },
  {
    cat: 'Idioma',
    wcag: '3.1.1',
    level: 'A',
    title: 'Atributo lang na tag <html>',
    detail: 'lang="pt-BR" orienta sintetizadores de voz, hifenização e ortografia. Sem isso, leitores leem com sotaque errado.',
  },
  {
    cat: 'Idioma',
    wcag: '3.1.2',
    level: 'AA',
    title: 'Trechos em outro idioma marcados',
    detail: '<span lang="en">A List Apart</span> evita que o leitor pronuncie "a list apart" em português.',
  },
  {
    cat: 'Touch',
    wcag: '2.5.5',
    level: 'AAA',
    title: 'Alvos de toque de 44×44px (mínimo) ou 48×48px (ideal)',
    detail: 'Inclui padding clicável invisível se necessário. Fundamental para Parkinson, artrite, uso com uma mão no transporte público.',
  },
  {
    cat: 'Touch',
    wcag: '2.5.1',
    level: 'A',
    title: 'Gestos multiponto têm alternativa simples',
    detail: 'Pinch-zoom, rotação, swipe custom devem ter botões equivalentes. Muitos usuários não têm a motricidade fina.',
  },
  {
    cat: 'Touch',
    wcag: '2.5.2',
    level: 'A',
    title: 'Ação acontece no "pointer up", não "down"',
    detail: 'Permite ao usuário arrastar para fora e cancelar. Impressionantemente comum em componentes custom.',
  },
  {
    cat: 'ARIA',
    wcag: '4.1.2',
    level: 'A',
    title: 'ARIA só quando HTML nativo não basta',
    detail: 'Primeira regra do ARIA: não use ARIA. Segunda: use HTML nativo. Só parta para aria-* em componentes custom complexos.',
  },
  {
    cat: 'ARIA',
    wcag: '4.1.2',
    level: 'A',
    title: 'aria-label não duplica texto visível',
    detail: 'Se o botão já diz "Baixar relatório", aria-label="baixar" substitui o nome acessível — o leitor lê só "baixar". Deixe o nativo funcionar.',
  },
  {
    cat: 'ARIA',
    wcag: '4.1.3',
    level: 'AA',
    title: 'aria-live para conteúdo que muda',
    detail: 'Barra de progresso, contadores, resultados de busca. aria-live="polite" anuncia sem interromper. "assertive" só para erros críticos.',
  },
  {
    cat: 'Zoom',
    wcag: '1.4.4',
    level: 'AA',
    title: 'Zoom até 200% sem perda de conteúdo',
    detail: 'Sem scroll horizontal em viewports de 320px após zoom 200%. Layout fluido obrigatório. Nunca use "user-scalable=no" na meta viewport.',
  },
  {
    cat: 'Zoom',
    wcag: '1.4.10',
    level: 'AA',
    title: 'Reflow: conteúdo fluido em 320px de largura',
    detail: 'Equivale a zoom 400% num desktop. Nada importante fica invisível. Tabelas complexas podem manter scroll horizontal mas precisam de alternativa.',
  },
  {
    cat: 'Zoom',
    wcag: '1.4.12',
    level: 'AA',
    title: 'Espaçamento de texto customizável',
    detail: 'line-height ≥ 1.5, letter-spacing ≥ 0.12em, word-spacing ≥ 0.16em, paragraph-spacing ≥ 2x line-height — nada corta ou sobrepõe.',
  },
  {
    cat: 'Erros',
    wcag: '3.3.1',
    level: 'A',
    title: 'Erros identificados em texto claro',
    detail: 'Aponte campo específico, descreva o problema em linguagem simples. "CEP inválido: use o formato 00000-000".',
  },
  {
    cat: 'Erros',
    wcag: '3.3.4',
    level: 'AA',
    title: 'Reversibilidade em operações destrutivas',
    detail: 'Exclusão confirmada, envio revisável, compra com resumo antes de pagar. Dá segurança para quem tem medo de errar.',
  },
  {
    cat: 'Cognitivo',
    wcag: '3.2.4',
    level: 'AA',
    title: 'Componentes iguais têm comportamento igual',
    detail: 'Se dois ícones de lixeira existem, ambos excluem. Inconsistência quebra o modelo mental de quem processa devagar.',
  },
  {
    cat: 'Cognitivo',
    wcag: '3.1.3',
    level: 'AAA',
    title: 'Linguagem simples e direta',
    detail: 'Frases curtas, voz ativa, termos técnicos explicados na primeira ocorrência. PT-BR do dia a dia, não formalismo acadêmico.',
  },
  {
    cat: 'Cognitivo',
    wcag: '2.2.1',
    level: 'A',
    title: 'Tempo limite é opcional ou extensível',
    detail: 'Sessões, formulários, ofertas. Ou não expire, ou permita estender, ou avise com antecedência e ofereça retomar.',
  },
  {
    cat: 'Cognitivo',
    wcag: '3.3.5',
    level: 'AAA',
    title: 'Ajuda contextual disponível',
    detail: 'Tooltips, textos de ajuda, exemplos preenchidos. Pode ser via ícone de "?". Sempre acessível via teclado.',
  },
  {
    cat: 'Estrutura',
    wcag: '1.3.2',
    level: 'A',
    title: 'Ordem do DOM reflete ordem visual',
    detail: 'CSS muda apresentação sem alterar sequência lógica. Flexbox `order` e `grid-area` podem criar dissonância — teste com leitor de tela.',
  },
  {
    cat: 'Estrutura',
    wcag: '2.4.6',
    level: 'AA',
    title: 'Headings e labels descrevem tópico/propósito',
    detail: 'Escaneáveis: "Endereço de entrega", "Métodos de pagamento" — não "Informações" genérico.',
  },
  {
    cat: 'Estrutura',
    wcag: '2.4.10',
    level: 'AAA',
    title: 'Seções com headings',
    detail: 'Cada bloco principal tem um heading próprio, mesmo que visualmente sutil. Facilita navegação por tópicos.',
  },
  {
    cat: 'Estrutura',
    wcag: '1.3.1',
    level: 'A',
    title: 'Tabelas de dados com <th> e escopo',
    detail: 'scope="col" ou scope="row". Use <caption> para descrever a tabela. Nunca use tabela para layout visual.',
  },
  {
    cat: 'Foco',
    wcag: '2.4.11',
    level: 'AA',
    title: 'Elemento focado não é coberto por overlay',
    detail: 'Headers sticky, cookie banners, chat bubbles — todos precisam ceder ao elemento focado ou usar scroll-padding.',
  },
  {
    cat: 'Foco',
    wcag: '2.4.12',
    level: 'AAA',
    title: 'Elemento focado totalmente visível',
    detail: 'Nenhuma parte do controle focado fica fora da viewport ou parcialmente coberta. Scroll automático deve trazer o foco inteiro para dentro.',
  },
  {
    cat: 'Foco',
    wcag: '2.4.13',
    level: 'AAA',
    title: 'Foco visível tem área ≥ 2px de perímetro',
    detail: 'Contraste ≥ 3:1 contra estado não focado. Vale tanto um outline quanto uma mudança de fundo — se medir.',
  },
  {
    cat: 'Input',
    wcag: '1.3.5',
    level: 'AA',
    title: 'autocomplete correto em todos os campos',
    detail: 'Nome, email, telefone, endereço, CPF (use x-cpf), CEP (x-cep) — lista completa em HTML Living Standard.',
  },
  {
    cat: 'Input',
    wcag: '2.5.7',
    level: 'AA',
    title: 'Arrastar tem alternativa por toque simples',
    detail: 'Reordenar lista, dismiss de card, ajuste de slider — botões +/- e atalhos de teclado equivalentes sempre.',
  },
  {
    cat: 'Input',
    wcag: '2.5.8',
    level: 'AA',
    title: 'Alvos de toque respeitam 24×24px (mínimo absoluto)',
    detail: 'Novo em WCAG 2.2. Espaçamento suficiente entre alvos, ou alvo com área efetiva ≥ 24px se pequeno.',
  },
  {
    cat: 'Global',
    wcag: 'LBI',
    level: 'LEI',
    title: 'Selo de acessibilidade visível',
    detail: 'Lei Brasileira de Inclusão (13.146/2015) exige declaração acessível. Link no footer apontando para política de acessibilidade.',
  },
  {
    cat: 'Global',
    wcag: 'eMAG',
    level: 'BR',
    title: 'Conformidade declarada (eMAG ou WCAG)',
    detail: 'eMAG para governo brasileiro; WCAG 2.2 AA mínimo para privado. Publique relatório público de conformidade e métricas.',
  },
  {
    cat: 'Global',
    wcag: '2.4.5',
    level: 'AA',
    title: 'Busca e sitemap disponíveis',
    detail: 'Duas formas de encontrar conteúdo: navegação hierárquica + busca (ou sitemap ou menu de links).',
  },
  {
    cat: 'Global',
    wcag: '1.4.13',
    level: 'AA',
    title: 'Conteúdo hover/foco dismissível e persistente',
    detail: 'Tooltip abre no hover? Pode ser fechado com Esc sem mover o mouse, e permanece enquanto o ponteiro está sobre ele.',
  },
  {
    cat: 'Documentação',
    wcag: '-',
    level: 'DOC',
    title: 'Declaração de acessibilidade pública',
    detail: 'Inclui: padrão adotado (WCAG 2.2 AA), exceções conhecidas, canal para reportar barreiras, data da última avaliação, responsável.',
  },
  {
    cat: 'Documentação',
    wcag: '-',
    level: 'DOC',
    title: 'Testes com usuários reais',
    detail: 'Teste com pessoas com deficiências visuais, motoras, auditivas, cognitivas. Automação pega ~30% dos problemas; o resto só teste real revela.',
  },
  {
    cat: 'Documentação',
    wcag: '-',
    level: 'DOC',
    title: 'Processo de revisão em cada release',
    detail: 'Checklist (este!) rodado antes de qualquer deploy. Bloqueio automático para violações críticas. A11y é qualidade, não extra.',
  },
  {
    cat: 'Documentação',
    wcag: '-',
    level: 'DOC',
    title: 'Time treinado em acessibilidade',
    detail: 'Devs, designers e PMs com ao menos uma formação ao ano. Não centralizar em uma única pessoa — é cultura, não função.',
  },
  {
    cat: 'Semântica',
    wcag: '1.3.1',
    level: 'A',
    title: 'Botões e links usados corretamente',
    detail: '<a> muda de URL/seção; <button> executa ação. Confundir os dois quebra expectativas: leitor de tela anuncia "link" mas a ação é modal.',
  },
  {
    cat: 'Formulários',
    wcag: '3.3.9',
    level: 'AA',
    title: 'Sem CAPTCHA que dependa só de imagem',
    detail: 'reCAPTCHA v3 (invisível) ou alternativas. Áudio alternativo de baixíssima qualidade não conta. Prefira honeypot ou validação silenciosa.',
  },
  {
    cat: 'Contraste',
    wcag: '1.4.6',
    level: 'AAA',
    title: 'Contraste elevado em material crítico',
    detail: 'Texto ≥ 7:1 (WCAG) ou Lc 90+ (APCA) em documentos legais, instruções médicas, bulas. Nível AAA vale o esforço.',
  },
  {
    cat: 'Teclado',
    wcag: '2.1.4',
    level: 'A',
    title: 'Atalhos de tecla únicos podem ser desativados',
    detail: 'Se atalhos de letra única existem (ex: "j" pula próximo), ofereça toggle. Usuários de voz acionam sem querer o tempo todo.',
  },
  {
    cat: 'ARIA',
    wcag: '4.1.2',
    level: 'A',
    title: 'Roles customizados só quando absolutamente necessário',
    detail: 'role="button" num <div> traz dor: você reimplementa teclado, estados, leitura. Use <button> e economize 50 linhas.',
  },
  {
    cat: 'Mídia',
    wcag: '1.2.5',
    level: 'AA',
    title: 'Transcrições para podcasts/áudios',
    detail: 'Texto completo da narrativa, incluindo identificação de falantes. Beneficia surdos e SEO.',
  },
  {
    cat: 'Foco',
    wcag: '3.2.1',
    level: 'A',
    title: 'Foco não dispara mudança de contexto',
    detail: 'Focar num select não abre popup. Focar num campo não submete formulário. Ação acontece por Enter/Space, não por Tab.',
  },
];
